### ISSUE TITLE
f32 for watts / voltage may loose precision

### ISSUE THREAD

**Issue by fkohlgrueber** [rksm/fritz-homeautomation-rs#1]
Hi,

I'm writing a program to collect consumption data from a Fritz!Dect 2XX plug and this library has been working great for this. 

The only issue I found is that voltage and watts are exposed as f32 values which may loose precision. I'd like to use the values as they're provided by the Fritz API. I'm currently using a local fork of the library where I changed the two values from f32 to u32, something like this: 

```diff
diff --git a/fritzapi/src/devices/fritz_dect_2xx.rs b/fritzapi/src/devices/fritz_dect_2xx.rs
index 9f62e78..7aa6842 100644
--- a/fritzapi/src/devices/fritz_dect_2xx.rs
+++ b/fritzapi/src/devices/fritz_dect_2xx.rs
@@ -4,8 +4,8 @@ pub struct FritzDect2XX {
     pub name: String,
     pub productname: String,
     pub on: bool,
-    pub voltage: f32,
-    pub watts: f32,
+    pub millivolts: u32,
+    pub milliwatts: u32,
     pub energy_in_watt_h: u32,
     pub celsius: f32,
 }
diff --git a/fritzapi/src/devices/mod.rs b/fritzapi/src/devices/mod.rs
index 4377b5b..beba156 100644
--- a/fritzapi/src/devices/mod.rs
+++ b/fritzapi/src/devices/mod.rs
@@ -59,8 +59,8 @@ impl AVMDevice {
                         productname: productname.clone(),
                         name: name.clone(),
                         on: *state,
-                        voltage: *voltage as f32 * 0.001,
-                        watts: *power as f32 * 0.001,
+                        millivolts: *voltage,
+                        milliwatts: *power,
                         energy_in_watt_h: *energy,
                         celsius: celsius.parse::<f32>().unwrap_or_default() * 0.1,
                         // raw: dev,
```

What do you think about this? Would you be open to accept a PR for the changes above? 

Thanks in advance!

**Comment by rksm** [comment]
Hi there! Sorry for the late response. Yes, a PR would be awesome. Thank you!

**Comment by felixwrt** [comment]
No problem, this isn't urgent in any way. I just opened a PR with the changes described above. Can you have a look? If it looks good to you, it'd be great to release a new version such that I can directly use the lib in my project.
