### ISSUE TITLE
Trigger higher refresh rate for Fritz!Dect 2XX

### ISSUE THREAD

**Issue by felixwrt** [rksm/fritz-homeautomation-rs#3]
I'm using this library to collect power consumption data from a Fritz!Dect 2XX smart power plug. I found out that I get new data every 2 minutes usually, but the update interval decreases to ~10 seconds when opening the Fritz app/ web page. I did a bit of digging and found that a simple http request is enough to activate the higher data update frequency (new data every 10s) for some time. When sending this http request periodically, it's possible to permanently receive 10s time resolution data from the plug. 

Now the question: Would you be interested to include this request in your library? I could prepare a draft PR if you like.

**Comment by rksm** [comment]
Yep, sounds good! Thank you!
